### ISSUE TITLE
Develop static site with single page using clear HTML 

### ISSUE THREAD

**Issue by Alexvsalexvsalex** [SophiaLaz/WebProject#1]
I expect single-page site with \<img\> and \<div\> tags. Images can be saved to files. But it also can contain any other tags and .css style files. 
Good tutorial: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started

**Comment by SophiaLaz** [comment]
This task is in [that](https://github.com/SophiaLaz/WebProject/commit/86a67852aa437ceeb8e61e6891771c18bf85bc37) commit.
