### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Alexvsalexvsalex** [SophiaLaz/WebProject#10]
Tests are necessary. Excellent time for writing test when new function just created. In ideal world every method must be tested, but we will check only backend part that connected with data transformation.
In-memory DB (when all data is stored to RAM) with real interface is useful here, because unit tests doesn't use external services.
PyTest guide: https://habr.com/ru/articles/269759/

**Comment by SophiaLaz** [comment]
OK, I've added a test for my backend, which is related to data transformation.
Commit is [here](https://github.com/SophiaLaz/WebProject/commit/315c040a329ea9ecdae42a8ad5e5b0aaa071bfc9)
