### ISSUE TITLE
Use React framework

### ISSUE THREAD

**Issue by Alexvsalexvsalex** [SophiaLaz/WebProject#2]
React components should be added to clear HTML site.
Encoding images to Base64 is the most convenient way to preserve image bytes in code or database.
React helps to create interactive services, so here switching pages can be made.
Tutorial: https://react.dev/learn, https://www.delftstack.com/howto/html/html-img-base64/

**Comment by SophiaLaz** [comment]
I created react-project [here](f3460189acb736803206157307a4ec19cf798501) with similar one-page site :rocket:
Then I converted actor's image to Base64 format and exported it from a `.js` file [here](69e4e73d74cae107a0830f871f06d124f3a125a0).
