### ISSUE TITLE
Make Flask backend

### ISSUE THREAD

**Issue by Alexvsalexvsalex** [SophiaLaz/WebProject#3]
Include Flask framework to sources. On this phase one endpoint will be enough: `/objects/{id}` - get json info about object with specified id (image plus description).
Useful link: https://skillbox.ru/media/code/freymvork-flask-kak-on-rabotaet-i-zachem-nuzhen/

**Comment by SophiaLaz** [comment]
I developed backend system with one point. For this I:
 - added information about actors in separate files;
 - created server with CORS support for sends data for client;
 - changed the client - now it receives data from the server.

All changes in [that](6545fddc4816718219aec72edc9ee589efba9898) commit.
