### ISSUE TITLE
Support DB storage

### ISSUE THREAD

**Issue by Alexvsalexvsalex** [SophiaLaz/WebProject#4]
Databases may be one of two types: SQL and noSQL. Information about every object has strict format, so both types are able in task. My offer is to use PostgreSQL with 3 columns: `id`, `description`, `image`.
This task will produce new python module with DB functions.
Some links: https://ru.hexlet.io/blog/posts/python-postgresql, https://gb.ru/blog/rabota-s-bazami-dannykh-sql/

**Comment by SophiaLaz** [comment]
I created an SQL database using PostgreSQL with a table `actors`. I have added information about one actor for a single-page website to this table. 
Then I changed getting information on my server - now there are two methods: 
 - from files;
 - from an SQL database.

Commit is [here](https://github.com/SophiaLaz/WebProject/commit/04dedee98138ab7830f35a0331cb63d32030cb66).
